### ISSUE TITLE
Generate ingress rules kubernetes version 1.20.0 or higher

### ISSUE THREAD

**Issue by iglrivosc** [prefapp/prefapp-helm#167]
### Steps to replicate the problem

I generate an ingress rule and call to **ph.ingress.render** who require to pass a variable called version with the value of kubernetes cluster version.

I pass this variable with the value of {{ .Capabilities.KubeVersion }} and it works selecting the correct api version but it fails when generate the ingress rules.

### File example
Chart file:

``` 
{{- define "example.ingress" -}}
version: {{ .Capabilities.KubeVersion }}
name: {{ .Release.Name}}-{{ .Values.RuleName }}
hosts: {{ .Values.hosts | toYaml | nindent 2 }}
{{ end }} 

{{ include "ph.ingress.render" (include "example.ingress" . | fromYaml) }}

```

Values file:
```
hosts:
   - host: myhost.example.com
     rules_path:
        - service: myservice
          port: 80
          path: /

```
apiVersion output:

```
apiVersion: networking.k8s.io/v1
kind: Ingress

```

Ingress rules output:

```
  - host: "myhost.example.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: myservice
          servicePort: 80

```
