### ISSUE TITLE
Can't change apiVersion on ingress.yaml

### ISSUE THREAD

**Issue by pablosanchezpaz** [prefapp/prefapp-helm#41]
Can't force apply version 1.20 to use apiVersion: networking.k8s.io/v1

If I force the value in the ingress.yaml it doesn't get replaced

default is: networking.k8s.io/v1beta1

**Comment by frmadem** [comment]
Yes @pablosanchezpaz you can if you set a version on your data:

```yaml

{{ describe "my-ingress.data" }}

# for a specific kubernetes version
version: "1.19.7"

# or you can set an autodetect by using the proper builtin object
version: {{ .Capabilities.KubeVersion.Version }}

{{ end }}

```
